//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocoInfo.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locomotive
    {
        public int ID { get; set; }
        public int DirectorateNumber { get; set; }
        public string DepotDirectorate { get; set; }
        public string TypeOfTraction { get; set; }
        public string TypeOfMovement { get; set; }
        public string LocomotiveSeries { get; set; }
        public string LocomotiveSectionNumber { get; set; }
        public string SectionNumber { get; set; }
        public System.DateTime TurningDate { get; set; }
        public string GroupOfReasons { get; set; }
        public string Reason { get; set; }
        public string KP { get; set; }
        public int SeatNumber { get; set; }
        public int MonthOfTurning { get; set; }
        public string TheCompanyThatProducedTheTurning { get; set; }
        public string DirectorateOfTheCompanyThatProducedTheTurning { get; set; }
        public Nullable<long> MileagePerYear { get; set; }
    }
}
